---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-service
  labels:
    app: bootstrap-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      targetPort: 80
  selector:
    app: bootstrap
